# Generated by Django 4.2.7 on 2023-11-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomo', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
